# fly.toml app configuration file generated for wishlist-fly on 2024-08-13T19:41:58+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'wishlist-fly'
primary_region = 'lhr'
console_command = 'php /var/www/html/artisan tinker'

[build]
  [build.args]
    NODE_VERSION = '18'
    PHP_VERSION = '8.2'

[env]
  APP_ENV = "production"
  DB_CONNECTION = "pgsql"
  APP_URL = 'https://wishlist-fly.fly.dev/'
  LOG_CHANNEL = 'stderr'
  LOG_LEVEL = 'info'
  LOG_STDERR_FORMATTER = 'Monolog\Formatter\JsonFormatter'
  SESSION_DRIVER = 'cookie'
  SESSION_SECURE_COOKIE = 'true'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[deploy]
  release_command = "php /var/www/html/artisan migrate --force"
  [processes]
  app=""
  cron="cron -f"
  worker = "php artisan queue:listen"

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
